### ISSUE TITLE
Assigning Value to a bin

### ISSUE THREAD

**Issue by JovinHoon91** [Asymmetrik/leaflet-d3#5]
Hi, 

May i know how may i assign a value i created to the hex bin? currently, the situation is this:
                       value: function(d){   
				return d.length;
                                
			},
But i want
                       value: function(d){   
				return d[2];
                                
			},
Would appreciate your help on this. Thanks

**Comment by reblace** [comment]
The way the hexbin layer works is that you provide an array of data, where each element in the array has a lat/long. Those points are binned into a grid of hexagons. Each hexagon will contain zero or more data elements.

Then, the **value** accessor function is passed the array of points for each bin so that you can generate a value that represents that bin. In the __examples/hexbins/basic.html__ example, the value function returns the length of the array. But, you could also perform some operation over all of the values in the array (eg. summation, average, product, etc).

**Comment by JovinHoon91** [comment]
Hi,

Thanks alot for the clarification!

**Comment by reblace** [comment]
Closing as I think I provided the required feedback.

**Comment by lrpatterson** [comment]
Does this still work if used in combination with `hexLayer.radiusValue`?  

EX:

```
hexLayer.radiusValue(function(d) { 
    return d.reduce(function(a, b) {
        return a + b;
    });
});
```
