### ISSUE TITLE
Labeling the cells by the number of aggregated points

### ISSUE THREAD

**Issue by kannes** [Asymmetrik/leaflet-d3#56]
Is it possible to add the number of aggregated points as label to each hexagon?

**Comment by reblace** [comment]
It's certainly possible. You can dig through the code that handles the hover pop-ups to see how to access the counts. And, you could add some code to your app that uses d3.selectAll to add the labels to the hexbins.

**Comment by kannes** [comment]
I made it!

```
d3.select('svg').selectAll("g.hexbin-container")
  .append("text")
  .attr("dy", ".35em")  // magic number to vertically center the text, probably in relation to font-size...
  .attr("text-anchor", "middle")  // horizontally center text in the hexbin
  .attr("x", function(d) { return d.x; })
  .attr("y", function(d) { return d.y; })
  .text(function(d) { return d.length; })  // number of points aggregated in the hexbin
;

```

Can you give me a pointer on how to make this happen after any map interaction like zoom and pan?

**Comment by reblace** [comment]
Leaflet exposes map events for zoom and move (which is pan). https://leafletjs.com/reference-1.3.4.html#map-zoomend

You can register callbacks for 'moveend' and put your code into there. That's what the leaflet-d3 plugin done.

You'll want to make sure you properly handle enter/update correctly so that you don't end up repeatedly adding the same labels to the elements. Unless, you remove all the labels first, and then add new ones (but that'll be less efficient).

**Comment by kannes** [comment]
Finally coming back to open issues. I have no idea how to do all that, sorry. JavaScript and D3 are mystical lands for me. ;)

**Comment by reblace** [comment]
No worries. Glad to help. If you need more help w/code examples and stuff, I'd suggest you ask on Stack Overflow and tag with leaflet and d3.js tags. There's a pretty big community over there that can help you out with more general questions about d3 and event handling and stuff.

**Comment by reblace** [comment]
Closing as we've provided help and it doesn't sound like there is a specific issue left to address. As mentioned earlier in the thread, Stack Overflow is the appropriate resource to leverage for general support and help if there is not a specific bug or defect to report. Thanks!
